export const data = [
  {
    id: 1,
    name: "Frontend Uzmanlık Sınıfı",
    teacher: "Furkan Özay",
    period: "9",
    location: "Class 147",
    img: "./img/bg-students.png",
    students: [
      {
        id: 1,
        name: "Berat",
        surname: "Dimen",
        email: "berat.dimen@example.com",
        schoolNo: "20104723",
        tckn: "12345678901",
        gender: "Male",
        attendance: 7,
        grade: 85,
        birthYear: 2000,
      },
      {
        id: 2,
        name: "Öznur",
        surname: "Dimen",
        email: "oznur.dimen@example.com",
        schoolNo: "20104724",
        tckn: "12345678902",
        gender: "Female",
        attendance: 3,
        grade: 90,
        birthYear: 1999,
      },
      {
        id: 3,
        name: "Sema",
        surname: "Bekdemir",
        email: "sema.bekdemir@example.com",
        schoolNo: "20104725",
        tckn: "12345678903",
        gender: "Female",
        attendance: 8,
        grade: 88,
        birthYear: 1998,
      },
      {
        id: 4,
        name: "Baki",
        surname: "Çağlayan",
        email: "baki.caglayan@example.com",
        schoolNo: "20104726",
        tckn: "12345678904",
        gender: "Male",
        attendance: 5,
        grade: 70,
        birthYear: 2001,
      },
      {
        id: 5,
        name: "Selin",
        surname: "Kaya",
        email: "selin.kaya@example.com",
        schoolNo: "20104727",
        tckn: "12345678917",
        gender: "Female",
        attendance: 2,
        grade: 65,
        birthYear: 1997,
      },
      {
        id: 6,
        name: "Can",
        surname: "Yıldırım",
        email: "can.yildirim@example.com",
        schoolNo: "20104728",
        tckn: "12345678918",
        gender: "Male",
        attendance: 9,
        grade: 95,
        birthYear: 1996,
      },
      {
        id: 7,
        name: "Derya",
        surname: "Kurt",
        email: "derya.kurt@example.com",
        schoolNo: "20104738",
        tckn: "12345678916",
        gender: "Female",
        attendance: 6,
        grade: 85,
        birthYear: 2002,
      },
      {
        id: 8,
        name: "Emre",
        surname: "Aydın",
        email: "emre.aydin@example.com",
        schoolNo: "20104739",
        tckn: "12345678917",
        gender: "Male",
        attendance: 8,
        grade: 88,
        birthYear: 2001,
      },
      {
        id: 9,
        name: "Zeynep",
        surname: "Şentürk",
        email: "zeynep.senturk@example.com",
        schoolNo: "20104740",
        tckn: "12345678918",
        gender: "Female",
        attendance: 9,
        grade: 92,
        birthYear: 1998,
      },
      {
        id: 10,
        name: "Mehmet",
        surname: "Durmaz",
        email: "mehmet.durmaz@example.com",
        schoolNo: "20104741",
        tckn: "12345678919",
        gender: "Male",
        attendance: 7,
        grade: 83,
        birthYear: 1999,
      },
      {
        id: 11,
        name: "Furkan",
        surname: "Kaya",
        email: "furkan.kaya@example.com",
        schoolNo: "20104742",
        tckn: "12345678920",
        gender: "Male",
        attendance: 10,
        grade: 94,
        birthYear: 2000,
      },
    ],
  },
  {
    id: 2,
    name: "Backend Uzmanlık Sınıfı",
    teacher: "Orhan Ekici",
    period: "9",
    location: "Class 148",
    img: "./img/bg-students-2.jpg",
    students: [
      {
        id: 1,
        name: "Ahmet",
        surname: "Yılmaz",
        email: "ahmet.yilmaz@example.com",
        schoolNo: "20104729",
        tckn: "12345678905",
        gender: "Male",
        attendance: 4,
        grade: 72,
        birthYear: 1995,
      },
      {
        id: 2,
        name: "Ayşe",
        surname: "Demir",
        email: "ayse.demir@example.com",
        schoolNo: "20104730",
        tckn: "12345678906",
        gender: "Female",
        attendance: 7,
        grade: 89,
        birthYear: 1994,
      },
      {
        id: 3,
        name: "Murat",
        surname: "Yıldız",
        email: "murat.yildiz@example.com",
        schoolNo: "20104731",
        tckn: "12345678907",
        gender: "Male",
        attendance: 5,
        grade: 80,
        birthYear: 1993,
      },
      {
        id: 4,
        name: "Zeynep",
        surname: "Karadağ",
        email: "zeynep.karadag@example.com",
        schoolNo: "20104732",
        tckn: "12345678908",
        gender: "Female",
        attendance: 3,
        grade: 78,
        birthYear: 1992,
      },
      {
        id: 5,
        name: "Efe",
        surname: "Kurt",
        email: "efe.kurt@example.com",
        schoolNo: "20104733",
        tckn: "12345678919",
        gender: "Male",
        attendance: 6,
        grade: 82,
        birthYear: 1991,
      },
      {
        id: 6,
        name: "Deniz",
        surname: "Güler",
        email: "deniz.guler@example.com",
        schoolNo: "20104734",
        tckn: "12345678920",
        gender: "Female",
        attendance: 8,
        grade: 87,
        birthYear: 1990,
      },
      {
        id: 7,
        name: "Baran",
        surname: "Arslan",
        email: "baran.arslan@example.com",
        schoolNo: "20104733",
        tckn: "12345678911",
        gender: "Male",
        attendance: 5,
        grade: 76,
        birthYear: 2003,
      },
      {
        id: 8,
        name: "Selin",
        surname: "Yılmaz",
        email: "selin.yilmaz@example.com",
        schoolNo: "20104734",
        tckn: "12345678912",
        gender: "Female",
        attendance: 10,
        grade: 93,
        birthYear: 1999,
      },
      {
        id: 9,
        name: "Oğuz",
        surname: "Şahin",
        email: "oguz.sahin@example.com",
        schoolNo: "20104735",
        tckn: "12345678913",
        gender: "Male",
        attendance: 8,
        grade: 87,
        birthYear: 2000,
      },
      {
        id: 10,
        name: "Elif",
        surname: "Koç",
        email: "elif.koc@example.com",
        schoolNo: "20104736",
        tckn: "12345678914",
        gender: "Female",
        attendance: 9,
        grade: 90,
        birthYear: 1998,
      },
      {
        id: 11,
        name: "Murat",
        surname: "Ersoy",
        email: "murat.ersoy@example.com",
        schoolNo: "20104737",
        tckn: "12345678915",
        gender: "Male",
        attendance: 7,
        grade: 82,
        birthYear: 1997,
      },
    ],
  },
  {
    id: 3,
    name: "Frontend Temel Sınıfı",
    teacher: "Nihat Duysak",
    period: "9",
    location: "Class 149",
    img: "./img/bg-students-3.jpg",
    students: [
      {
        id: 1,
        name: "Emre",
        surname: "Çetin",
        email: "emre.cetin@example.com",
        schoolNo: "20104735",
        tckn: "12345678909",
        gender: "Male",
        attendance: 6,
        grade: 83,
        birthYear: 1989,
      },
      {
        id: 2,
        name: "Merve",
        surname: "Koç",
        email: "merve.koc@example.com",
        schoolNo: "20104736",
        tckn: "12345678910",
        gender: "Female",
        attendance: 5,
        grade: 76,
        birthYear: 1992,
      },
      {
        id: 3,
        name: "Ece",
        surname: "Aydın",
        email: "ece.aydin@example.com",
        schoolNo: "20104737",
        tckn: "12345678911",
        gender: "Female",
        attendance: 9,
        grade: 91,
        birthYear: 1990,
      },
      {
        id: 4,
        name: "Ali",
        surname: "Vural",
        email: "ali.vural@example.com",
        schoolNo: "20104738",
        tckn: "12345678912",
        gender: "Male",
        attendance: 4,
        grade: 74,
        birthYear: 1994,
      },
      {
        id: 5,
        name: "Burcu",
        surname: "Turan",
        email: "burcu.turan@example.com",
        schoolNo: "20104739",
        tckn: "12345678921",
        gender: "Female",
        attendance: 2,
        grade: 60,
        birthYear: 1991,
      },
      {
        id: 6,
        name: "Hakan",
        surname: "Öztürk",
        email: "hakan.ozturk@example.com",
        schoolNo: "20104740",
        tckn: "12345678922",
        gender: "Male",
        attendance: 8,
        grade: 85,
        birthYear: 1988,
      },
      {
        id: 7,
        name: "Ahmet",
        surname: "Demir",
        email: "ahmet.demir@example.com",
        schoolNo: "20104729",
        tckn: "12345678907",
        gender: "Male",
        attendance: 6,
        grade: 74,
        birthYear: 2002,
      },
      {
        id: 8,
        name: "Ayşe",
        surname: "Güneş",
        email: "ayse.gunes@example.com",
        schoolNo: "20104730",
        tckn: "12345678908",
        gender: "Female",
        attendance: 8,
        grade: 89,
        birthYear: 2001,
      },
      {
        id: 9,
        name: "Kemal",
        surname: "Bozkurt",
        email: "kemal.bozkurt@example.com",
        schoolNo: "20104731",
        tckn: "12345678909",
        gender: "Male",
        attendance: 7,
        grade: 84,
        birthYear: 1999,
      },
      {
        id: 9,
        name: "Kemal",
        surname: "Bozkurt",
        email: "kemal.bozkurt@example.com",
        schoolNo: "20104731",
        tckn: "12345678909",
        gender: "Male",
        attendance: 7,
        grade: 84,
        birthYear: 1999,
      },
      {
        id: 9,
        name: "Kemal",
        surname: "Bozkurt",
        email: "kemal.bozkurt@example.com",
        schoolNo: "20104731",
        tckn: "12345678909",
        gender: "Male",
        attendance: 7,
        grade: 84,
        birthYear: 1999,
      },
      {
        id: 10,
        name: "Gizem",
        surname: "Özkan",
        email: "gizem.ozkan@example.com",
        schoolNo: "20104732",
        tckn: "12345678910",
        gender: "Female",
        attendance: 9,
        grade: 91,
        birthYear: 1998,
      },
    ],
  },
  {
    id: 4,
    name: "Backend Temel Sınıfı",
    teacher: "Barış Kahraman",
    period: "9",
    location: "Class 150",
    img: "./img/bg-students-4.jpg",
    students: [
      {
        id: 1,
        name: "Kemal",
        surname: "Taş",
        email: "kemal.tas@example.com",
        schoolNo: "20104741",
        tckn: "12345678913",
        gender: "Male",
        attendance: 7,
        grade: 88,
        birthYear: 1987,
      },
      {
        id: 2,
        name: "Aslı",
        surname: "Eren",
        email: "asli.eren@example.com",
        schoolNo: "20104742",
        tckn: "12345678914",
        gender: "Female",
        attendance: 5,
        grade: 84,
        birthYear: 1993,
      },
      {
        id: 3,
        name: "Kadir",
        surname: "Arslan",
        email: "kadir.arslan@example.com",
        schoolNo: "20104743",
        tckn: "12345678915",
        gender: "Male",
        attendance: 6,
        grade: 82,
        birthYear: 1992,
      },
      {
        id: 4,
        name: "Sibel",
        surname: "Deniz",
        email: "sibel.deniz@example.com",
        schoolNo: "20104744",
        tckn: "12345678916",
        gender: "Female",
        attendance: 8,
        grade: 89,
        birthYear: 1994,
      },
      {
        id: 5,
        name: "Yusuf",
        surname: "Yavuz",
        email: "yusuf.yavuz@example.com",
        schoolNo: "20104745",
        tckn: "12345678923",
        gender: "Male",
        attendance: 9,
        grade: 93,
        birthYear: 1985,
      },
      {
        id: 6,
        name: "Sema",
        surname: "Aksoy",
        email: "sema.aksoy@example.com",
        schoolNo: "20104724",
        tckn: "12345678902",
        gender: "Female",
        attendance: 9,
        grade: 90,
        birthYear: 1999,
      },
      {
        id: 7,
        name: "Ali",
        surname: "Kara",
        email: "ali.kara@example.com",
        schoolNo: "20104725",
        tckn: "12345678903",
        gender: "Male",
        attendance: 6,
        grade: 78,
        birthYear: 2001,
      },
      {
        id: 8,
        name: "Ece",
        surname: "Sönmez",
        email: "ece.sonmez@example.com",
        schoolNo: "20104726",
        tckn: "12345678904",
        gender: "Female",
        attendance: 8,
        grade: 88,
        birthYear: 1998,
      },
      {
        id: 9,
        name: "Deniz",
        surname: "Çelik",
        email: "deniz.celik@example.com",
        schoolNo: "20104727",
        tckn: "12345678905",
        gender: "Male",
        attendance: 10,
        grade: 92,
        birthYear: 1997,
      },
      {
        id: 10,
        name: "Merve",
        surname: "Yıldız",
        email: "merve.yildiz@example.com",
        schoolNo: "20104728",
        tckn: "12345678906",
        gender: "Female",
        attendance: 5,
        grade: 80,
        birthYear: 2000,
      },
    ],
  },
];
